name: "Puppet"
description: "Turn dashboards into nice pictures"
version: "1.15.0"
slug: "puppet"
homeassistant_api: true
init: false
arch:
  - aarch64
  - amd64
ports:
  10000/tcp: 10000
options:
  access_token: ""
schema:
  access_token: str
